/*
Copyright 2020 SIA Platform Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta2

import (
	autoscalingv2beta2 "k8s.io/api/autoscaling/v2beta2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// IntelligentHorizontalPodAutoscalerSpec defines the desired state of IntelligentHorizontalPodAutoscaler
type IntelligentHorizontalPodAutoscalerSpec struct {
	// Specifies the horizontalPodAutoscaler(v2beta2) that will be based on ihpa.
	HorizontalPodAutoscalerTemplate ExtendedHorizontalPodAutoscalerTemplateSpec `json:"template"`

	// ScaleBackend specifies which autoscaling backend IHPA manages.
	// When omitted, IHPA manages a HorizontalPodAutoscaler.
	ScaleBackend ScaleBackendSpec `json:"scaleBackend,omitempty"`

	// EstimatorPatchSpec specifies some config for estimator
	EstimatorPatchSpec EstimatorPatchSpec `json:"estimator,omitempty"`

	// MetricProvider is data source and destination of metrics datapoints.
	MetricProvider MetricProvider `json:"metricProvider"`
}

type ScaleBackendType string

const (
	// ScaleBackendTypeHPA uses a Kubernetes HorizontalPodAutoscaler generated by IHPA.
	ScaleBackendTypeHPA ScaleBackendType = "HPA"
	// ScaleBackendTypeKEDA uses a KEDA ScaledObject generated by IHPA.
	ScaleBackendTypeKEDA ScaleBackendType = "KEDA"
)

// ScaleBackendSpec defines which scaling backend is managed by IHPA.
type ScaleBackendSpec struct {
	// Type is the autoscaling backend type.
	// +kubebuilder:validation:Enum=HPA;KEDA
	// +kubebuilder:default=HPA
	Type ScaleBackendType `json:"type,omitempty"`

	// KEDA specifies KEDA ScaledObject configuration.
	KEDA *KEDAScaleBackendSpec `json:"keda,omitempty"`
}

// KEDAScaleBackendSpec defines configuration for a KEDA ScaledObject.
type KEDAScaleBackendSpec struct {
	// Labels are copied to the generated ScaledObject.
	Labels map[string]string `json:"labels,omitempty"`

	// Annotations are copied to the generated ScaledObject.
	Annotations map[string]string `json:"annotations,omitempty"`

	// EnvSourceContainerName is copied to ScaledObject spec.scaleTargetRef.envSourceContainerName.
	EnvSourceContainerName string `json:"envSourceContainerName,omitempty"`

	// PollingInterval is the interval in seconds to check each trigger.
	// +kubebuilder:validation:Minimum=1
	PollingInterval *int32 `json:"pollingInterval,omitempty"`

	// CooldownPeriod is the period in seconds to wait before scaling back to idle/min replicas.
	// +kubebuilder:validation:Minimum=0
	CooldownPeriod *int32 `json:"cooldownPeriod,omitempty"`

	// InitialCooldownPeriod is the delay in seconds before cooldown starts after ScaledObject creation.
	// +kubebuilder:validation:Minimum=0
	InitialCooldownPeriod *int32 `json:"initialCooldownPeriod,omitempty"`

	// IdleReplicaCount is the replica count KEDA scales down to when triggers are inactive.
	// +kubebuilder:validation:Minimum=0
	IdleReplicaCount *int32 `json:"idleReplicaCount,omitempty"`

	// Fallback specifies fallback replicas when scalers fail.
	Fallback *KEDAFallbackSpec `json:"fallback,omitempty"`

	// Advanced specifies advanced KEDA ScaledObject settings.
	Advanced *KEDAAdvancedSpec `json:"advanced,omitempty"`

	// Triggers are copied to the generated ScaledObject.
	Triggers []KEDATriggerSpec `json:"triggers,omitempty"`
}

// KEDAFallbackSpec defines KEDA fallback behavior when scalers fail.
type KEDAFallbackSpec struct {
	// FailureThreshold is the number of consecutive failures before fallback is applied.
	// +kubebuilder:validation:Minimum=1
	FailureThreshold int32 `json:"failureThreshold"`

	// Replicas is the fallback replica count.
	// +kubebuilder:validation:Minimum=0
	Replicas int32 `json:"replicas"`

	// Behavior is the fallback behavior.
	// +kubebuilder:validation:Enum=static;currentReplicas;currentReplicasIfHigher;currentReplicasIfLower;scalingModifiers
	Behavior string `json:"behavior,omitempty"`
}

// KEDAAdvancedSpec defines advanced KEDA ScaledObject settings.
type KEDAAdvancedSpec struct {
	// RestoreToOriginalReplicaCount controls whether the target returns to its original replica count
	// after the ScaledObject is deleted.
	RestoreToOriginalReplicaCount *bool `json:"restoreToOriginalReplicaCount,omitempty"`

	// HorizontalPodAutoscalerConfig specifies HPA options used by KEDA.
	HorizontalPodAutoscalerConfig *KEDAHorizontalPodAutoscalerConfigSpec `json:"horizontalPodAutoscalerConfig,omitempty"`

	// ScalingModifiers specifies KEDA composite metric scaling settings.
	ScalingModifiers *KEDAScalingModifiersSpec `json:"scalingModifiers,omitempty"`
}

// KEDAHorizontalPodAutoscalerConfigSpec defines options for the HPA created by KEDA.
type KEDAHorizontalPodAutoscalerConfigSpec struct {
	// Name is the name of the HPA resource KEDA creates.
	Name string `json:"name,omitempty"`

	// Behavior is copied to the HPA behavior field created by KEDA.
	// This is intentionally raw because the repository still depends on Kubernetes v0.17,
	// whose autoscaling/v2beta2 API does not include the behavior type.
	// +kubebuilder:pruning:PreserveUnknownFields
	Behavior *runtime.RawExtension `json:"behavior,omitempty"`
}

// KEDAScalingModifiersSpec defines KEDA composite metric scaling settings.
type KEDAScalingModifiersSpec struct {
	// Target defines the composed metric target value.
	Target string `json:"target,omitempty"`

	// ActivationTarget defines the composed metric activation target value.
	ActivationTarget string `json:"activationTarget,omitempty"`

	// MetricType defines the metric target type for the composed metric.
	// +kubebuilder:validation:Enum=AverageValue;Value
	MetricType string `json:"metricType,omitempty"`

	// Formula defines the expression for composing trigger values.
	Formula string `json:"formula,omitempty"`
}

// KEDATriggerSpec defines a KEDA trigger.
type KEDATriggerSpec struct {
	// Type is the KEDA scaler type.
	Type string `json:"type"`

	// Name is the optional trigger name.
	Name string `json:"name,omitempty"`

	// MetricType is the HPA metric target type KEDA exposes for this trigger.
	// +kubebuilder:validation:Enum=Utilization;AverageValue;Value
	MetricType string `json:"metricType,omitempty"`

	// Metadata is scaler-specific trigger metadata.
	Metadata map[string]string `json:"metadata,omitempty"`

	// AuthenticationRef references a KEDA TriggerAuthentication or ClusterTriggerAuthentication.
	AuthenticationRef *KEDAAuthenticationRef `json:"authenticationRef,omitempty"`

	// UseCachedMetrics controls KEDA trigger metric caching.
	UseCachedMetrics *bool `json:"useCachedMetrics,omitempty"`
}

// KEDAAuthenticationRef references a KEDA authentication resource.
type KEDAAuthenticationRef struct {
	// Name is the TriggerAuthentication or ClusterTriggerAuthentication name.
	Name string `json:"name"`

	// Kind is the authentication resource kind.
	// +kubebuilder:validation:Enum=TriggerAuthentication;ClusterTriggerAuthentication
	Kind string `json:"kind,omitempty"`
}

// HorizontalPodAutoscalerTemplateSpec describes the data a HPA should have when created from a template
type ExtendedHorizontalPodAutoscalerTemplateSpec struct {
	// Standard object's metadata of the hpas created from this template.
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Specification of the desired behavior of the hpa.
	Spec ExtendedHorizontalPodAutoscalerSpec `json:"spec,omitempty"`
}

type ExtendedHorizontalPodAutoscalerSpec struct {
	// -- copy from autoscaling.v2beta2 definition --
	ScaleTargetRef autoscalingv2beta2.CrossVersionObjectReference `json:"scaleTargetRef" protobuf:"bytes,1,opt,name=scaleTargetRef"`
	MinReplicas    *int32                                         `json:"minReplicas,omitempty" protobuf:"varint,2,opt,name=minReplicas"`
	MaxReplicas    int32                                          `json:"maxReplicas" protobuf:"varint,3,opt,name=maxReplicas"`
	// but use ExtendedMetricSpec
	Metrics []ExtendedMetricSpec `json:"metrics,omitempty" protobuf:"bytes,4,rep,name=metrics"`
	// ----------------------------------------------
}

// ExtendedMetricSpec is same as autoscaling.v2beta2 but including FittingJob spec
type ExtendedMetricSpec struct {
	// -- copy from autoscaling.v2beta2 definition --
	Type     autoscalingv2beta2.MetricSourceType      `json:"type" protobuf:"bytes,1,name=type"`
	Object   *autoscalingv2beta2.ObjectMetricSource   `json:"object,omitempty" protobuf:"bytes,2,opt,name=object"`
	Pods     *autoscalingv2beta2.PodsMetricSource     `json:"pods,omitempty" protobuf:"bytes,3,opt,name=pods"`
	Resource *autoscalingv2beta2.ResourceMetricSource `json:"resource,omitempty" protobuf:"bytes,4,opt,name=resource"`
	External *autoscalingv2beta2.ExternalMetricSource `json:"external,omitempty" protobuf:"bytes,5,opt,name=external"`
	// ----------------------------------------------

	// FittingJobPatchSpec specifies some config for fittingJob
	FittingJobPatchSpec FittingJobPatchSpec `json:"fittingJob,omitempty"`
}

// MetricSpec extract pure MetricSpec from ExtendedMetricSpec.
func (ems *ExtendedMetricSpec) MetricSpec() *autoscalingv2beta2.MetricSpec {
	return &autoscalingv2beta2.MetricSpec{
		Type:     ems.Type,
		Object:   ems.Object,
		Pods:     ems.Pods,
		Resource: ems.Resource,
		External: ems.External,
	}
}

// FittingJobPatchSpec defines some FittingJobSpec field for patch
type FittingJobPatchSpec struct {
	JobPatchSpec `json:",inline"`

	// Seasonality is time span of bunch metrics period.
	// This is defined as "daily", "weekly", "yearly", "auto".
	// +kubebuilder:validation:Enum=daily;weekly;yearly;auto
	// +kubebuilder:default=auto
	Seasonality string `json:"seasonality,omitempty"`

	// ExecuteOn is hour of executing daily fitting job.
	// Fitting job is executed on at around the hour.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=23
	// +kubebuilder:default=4
	ExecuteOn int32 `json:"executeOn,omitempty"`

	// ChangePointDetectionConfig is configuration for fittingjob change point detection.
	ChangePointDetectionConfig ChangePointDetectionConfig `json:"changePointDetectionConfig,omitempty"`

	// CustomConfig is custom configurationfor fittingjob.
	CustomConfig string `json:"customConfig,omitempty"`
}

// GenerateFittingJobSpec generate FittingJobSpec from FittingJobPatchSpec
func (fjps *FittingJobPatchSpec) GenerateFittingJobSpec() *FittingJobSpec {
	return &FittingJobSpec{
		JobPatchSpec:               fjps.JobPatchSpec,
		Seasonality:                fjps.Seasonality,
		ExecuteOn:                  fjps.ExecuteOn,
		ChangePointDetectionConfig: fjps.ChangePointDetectionConfig,
		CustomConfig:               fjps.CustomConfig,
	}
}

// EstimatorPatchSpec defines some EstimatorSpec field for patch
type EstimatorPatchSpec struct {
	// Mode is a way to adjust estimate metrics
	// when the metrics out of line.
	// +kubebuilder:validation:Enum=raw;adjust
	// +kubebuilder:default=adjust
	Mode string `json:"mode,omitempty"`

	// GapMinutes is gap time for generating forecast metrics.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:default=10
	GapMinutes int32 `json:"gapMinutes,omitempty"`
}

// GenerateEstimatorSpec generate EstimatorSpec from EstimatorPatchSpec
func (eps *EstimatorPatchSpec) GenerateEstimatorSpec() *EstimatorSpec {
	return &EstimatorSpec{
		Mode:       eps.Mode,
		GapMinutes: eps.GapMinutes,
	}
}

// MetricProvider defines inforamtion of metrics provider.
type MetricProvider struct {
	// Name is a name of provider
	Name string `json:"name,omitempty"`

	// Aggregation is the aggregation function used when querying metrics.
	// Valid values are: sum, min, max, count, avg.
	// +kubebuilder:validation:Enum=sum;min;max;count;avg
	// +kubebuilder:default=sum
	Aggregation string `json:"aggregation,omitempty"`

	// ProviderSource is source of metrics provider.
	// This is defined as ***ProviderSource.
	ProviderSource `json:",inline"`
}

// ProviderSources defines source of some providers.
type ProviderSource struct {
	Datadog    *DatadogProviderSource    `json:"datadog,omitempty"`
	Prometheus *PrometheusProviderSource `json:"prometheus,omitempty"`
}

// DatadogProviderSource defines parameters for accessing Datadog.
type DatadogProviderSource struct {
	// APIKey is for accessing some function and sending metrics.
	APIKey string `json:"apikey,omitempty"`

	// APPKey is for retrieving metrics.
	APPKey string `json:"appkey,omitempty"`

	// KeysFrom is list from APIKey and APPKey source object.
	// The keys are set by searching "APIKey" and "APPKey" variables.
	KeysFrom []corev1.EnvFromSource `json:"keysFrom,omitempty"`
}

// PrometheusProviderSource defines parameters for accessing Prometheus.
type PrometheusProviderSource struct {
	// URL is the address of the Prometheus server for querying metrics.
	URL string `json:"url,omitempty"`

	// PushgatewayURL is the address of the Prometheus Pushgateway for sending metrics.
	PushgatewayURL string `json:"pushgatewayUrl,omitempty"`
}

// IntelligentHorizontalPodAutoscalerStatus defines the observed state of IntelligentHorizontalPodAutoscaler
type IntelligentHorizontalPodAutoscalerStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion

// IntelligentHorizontalPodAutoscaler is the Schema for the intelligenthorizontalpodautoscalers API
// +kubebuilder:resource:shortName=ihpa
type IntelligentHorizontalPodAutoscaler struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   IntelligentHorizontalPodAutoscalerSpec   `json:"spec,omitempty"`
	Status IntelligentHorizontalPodAutoscalerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IntelligentHorizontalPodAutoscalerList contains a list of IntelligentHorizontalPodAutoscaler
type IntelligentHorizontalPodAutoscalerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IntelligentHorizontalPodAutoscaler `json:"items"`
}

func init() {
	SchemeBuilder.Register(&IntelligentHorizontalPodAutoscaler{}, &IntelligentHorizontalPodAutoscalerList{})
}
